force-app/main/default/objects/Dossier__c/Dossier__c.object-meta.xml
<CustomObject>
    <label>Dossier</label>
    <nameField>
        <label>Nom de Dossier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dossiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dossier__c/fields/Compte__c.field-meta.xml
<CustomField>
    <fullName>Compte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dossiers</relationshipLabel>
    <relationshipName>Dossiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RetrieveDossiersController.cls
public with sharing class RetrieveDossiersController {
    public RetrieveDossiersController() {

    }
    public static List<Dossier__c> getDossiers(String AccountId){
        List<Dossier__c> dossiers = [SELECT Id,Name FROM Dossier__c Where compte__c =: AccountId];
        return dossiers;
    }
    public static Dossier__c getDossierById(String dossierId){
        Dossier__c dossier = [SELECT Id,Name FROM Dossier__c Where Id =: dossierId];
        return dossier;
    }
    public static Dossier__c getDossierByName(String dossierName){
        Dossier__c dossier = [SELECT Id,Name FROM Dossier__c Where Name =: dossierName];
        return dossier;
    }
    public static Integer countAllDossiers() {
        return [SELECT COUNT() FROM Dossier__c];
    }
    public static List<Dossier__c> getDossiersCreatedAfter(Date createdAfter) {
        return [SELECT Id, Name, CreatedDate FROM Dossier__c WHERE CreatedDate > :createdAfter];
    }
    public static List<Dossier__c> getDossiersByNamePrefix(String namePrefix) {
        return [SELECT Id, Name FROM Dossier__c WHERE Name LIKE :namePrefix + '%'];
    }
}